version: '2'
volumes:
    mongo-data:
        driver: local
services:
    mongodb:
        image: mongo
        volumes:
            - mongo-data:/data/db
    helloexpress:
        image: node
        user: node
        working_dir: /app
        environment:
            - env=development
        volumes:
            - ./:/app
        entrypoint: node /app/bin/www
        ports:
            - 3000:3000
        depends_on:
            - mongodb
        links:
            - mongodb:mongodb
